from enum import Enum
class TokenJS(Enum):
    COMENTARIO_MULTILINEA=1
    RESERVADA_VAR=2
    IDENTIFICADOR=3
    SIGNO_IGUAL=4
    SIGNO_MAS=5
    SIGNO_POR=6
    SIGNO_MENOS=7
    SIGNO_DIVISION=8
    NUMERO=9
    PARENTESIS_APERTURA=10
    PARENTESIS_CIERRE=11
    RESERVADA_IF=12
    RESERVADA_ELSE=13
    SIGNO_MAYOR=14
    SIGNO_MENOR=15
    SIGNO_MAYOR_IGUAL=16
    SIGNO_MENOR_IGUAL=17
    COMPARACION_ABSTRACTA=18 #==
    CADENA_DE_TEXTO=19
    SIGNO_LLAVE_APERTURA=20
    PUNTO=21
    PUNTO_Y_COMA=51
    INCREMENTO_UNITARIO=22
    DECREMENTO_UNITARIO=23
    INCREMENTO=24
    DECREMENTO=25
    MULTIPLICACION=26
    COMPARACION_ESTRICTA=27 #===
    CONJUNCION=28
    DISYNCION=29
    DISTINTO=30
    NEGACION=31
    RESERVADA_CONSOLE=32
    RESERVADA_LOG=33
    RESERVADA_WHILE=34
    RESERVADA_DO=35
    RESERVADA_CONTINUE=36
    RESERVADA_BREAK=37
    RESERVADA_RETURN=38
    RESERVADA_TRUE=39
    RESERVADA_FALSE=40
    RESERVADA_FUNCTION=41
    DOS_PUNTOS=42
    ASIGNACION_LAMBDA=43
    METODO_CONSTRUCTOR=44
    RESERVADA_CLASS=45
    RESERVADA_THIS=46
    RESERVADA_MATH=47
    RESERVADA_POW=48
    COMENTARIO_LINEAL=49
    SIGNO_LLAVE_CIERRE=50
    DESCONOCIDO=100


