from enum import Enum
class TokenCSS(Enum):
    COMENTARIO=1
    SELECTOR=2
    LLAVE_APERTURA=3
    LLAVE_CIERRE=4
    DOS_PUNTOS=5
    PUNTO_Y_COMA=6
    IDENTIFICADOR=7
    REGLA=8
    NUMERO=9
    SIMBOLO_GUION=10
    SIMBOLO_ASTERISCO=11
    SIMBOLO_ALMOHADILLA=12
    SIMBOLO_PORCENTAJE=13
    COMA=19
    CADENA_DE_TEXTO=14
    UNIDAD_DE_MEDIDA=15
    PUNTO=16
    PARENTESIS_APERTURA=17
    PARENTESIS_CIERRE=18
    COMENTARIO_SIN_FINALIZAR=99
    CARACATER_DESCONOCIDO=100
# " " | ":" | "-" | "." | ";" 
# "%" | "#" | "{" | "(" |